const translations = {
    en: {
        docTitle: "Tetris Game",
        navLogoAlt: "Logo",
        navToggleLabel: "Toggle navigation",
        navHome: "Home",
        navCaro: "Play Caro",
        navTetris: "Tetris Game",
        navAbout: "About",
        navContact: "Contact",
        navImageTools: "Image Tools",
        tetrisTitle: "Tetris Game",
        tetrisSubtitle: "Use arrow keys to move and rotate pieces. Fill rows to score!",
        scoreLabel: "Score",
        linesLabel: "Lines",
        levelLabel: "Level",
        nextPieceLabel: "Next",
        startBtn: "Start",
        pauseBtn: "Pause",
        restartBtn: "Restart",
        hardDrop: "Hard Drop",
        gameOverTitle: "GAME OVER",
        highScoreLabel: "High Score", // <-- THÊM DÒNG NÀY

    },
    vi: {
        docTitle: "Game Xếp Hình",
        navLogoAlt: "Logo",
        navToggleLabel: "Chuyển đổi điều hướng",
        navHome: "Trang Chủ",
        navCaro: "Chơi Cờ Caro",
        navTetris: "Game Xếp Hình",
        navAbout: "Giới Thiệu",
        navContact: "Liên Hệ",
        navImageTools: "Cắt Ảnh",
        tetrisTitle: "Game Xếp Hình (Tetris)",
        tetrisSubtitle: "Sử dụng các phím mũi tên để di chuyển và xoay các khối. Lấp đầy các hàng để ghi điểm!",
        scoreLabel: "Điểm",
        linesLabel: "Hàng",
        levelLabel: "Cấp độ",
        nextPieceLabel: "Tiếp theo",
        startBtn: "Bắt Đầu",
        pauseBtn: "Tạm Dừng",
        restartBtn: "Chơi Lại",
        hardDrop: "Thả Nhanh",
        gameOverTitle: "KẾT THÚC",
        highScoreLabel: "Điểm Cao", // <-- THÊM DÒNG NÀY
    }
};